SCREEN_SIZE = 1280, 720
FPS = 60
TICK_RATE = 2
FRAMES_PER_TICK = FPS // TICK_RATE

TILE_SIZE = 64
PIXEL_SCALE = 2

SURFACE_FRICTION_COEFFICIENT = 0.2

HEALTH_VISIBILITY_TIME = 60

ANIMATION_FRAME_TIME = 10